services:
  - type: web
    name: imperiu-sui-luris
    env: node
    plan: free
    buildCommand: npm run render:build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
